In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
import seaborn as sns 
import plotly.express as px
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier


from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import pickle


age
sex
chest pain type (4 values)
resting blood pressure
serum cholestoral in mg/dl
fasting blood sugar > 120 mg/dl
resting electrocardiographic results (values 0,1,2)
maximum heart rate achieved
exercise induced angina
oldpeak = ST depression induced by exercise relative to rest
the slope of the peak exercise ST segment
number of major vessels (0-3) colored 

In [2]:
df = pd.read_csv('../csv files/heart.csv')
df.head(20)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    52    1   0       125   212    0        1      168      0      1.0   
1    53    1   0       140   203    1        0      155      1      3.1   
2    70    1   0       145   174    0        1      125      1      2.6   
3    61    1   0       148   203    0        1      161      0      0.0   
4    62    0   0       138   294    1        1      106      0      1.9   
5    58    0   0       100   248    0        0      122      0      1.0   
6    58    1   0       114   318    0        2      140      0      4.4   
7    55    1   0       160   289    0        0      145      1      0.8   
8    46    1   0       120   249    0        0      144      0      0.8   
9    54    1   0       122   286    0        0      116      1      3.2   
10   71    0   0       112   149    0        1      125      0      1.6   
11   43    0   0       132   341    1        0      136      1      3.0   
12   34    0   1       118   210    0        1      192      0      0.7   
13   51    1   0       140   298    0        1      122      1      4.2   
14   52    1   0       128   204    1        1      156      1      1.0   
15   34    0   1       118   210    0        1      192      0      0.7   
16   51    0   2       140   308    0        0      142      0      1.5   
17   54    1   0       124   266    0        0      109      1      2.2   
18   50    0   1       120   244    0        1      162      0      1.1   
19   58    1   2       140   211    1        0      165      0      0.0   

    slope  ca  thal  target  
0       2   2     3       0  
1       0   0     3       0  
2       0   0     3       0  
3       2   1     3       0  
4       1   3     2       0  
5       1   0     2       1  
6       0   3     1       0  
7       1   1     3       0  
8       2   0     3       0  
9       1   2     2       0  
10      1   0     2       1  
11      1   0     3       0  
12      2   0     2       1  
13      1   3     3       0  
14      1   0     0       0  
15      2   0     2       1  
16      2   1     2       1  
17      1   1     3       0  
18      2   0     2       1  
19      2   0     2       1

In [3]:
df['cp'].unique()

array([0, 1, 2, 3], dtype=int64)

In [4]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
df_train, df_test = train_test_split(df)

In [6]:
y_train = df_train.target
x_train = df_train.drop('target', axis = 1)
y_train

844    0
707    1
626    0
969    1
735    1
      ..
26     1
99     1
681    0
782    1
959    1
Name: target, Length: 768, dtype: int64

In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [8]:
sm = SMOTE()
x_train,y_train = sm.fit_resample(x_train,y_train)

In [9]:
y_test = df_test.target
x_test = df_test.drop('target', axis = 1)

In [10]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
502   46    0   2       142   177    0        0      160      1      1.4   
513   54    1   0       110   206    0        0      108      1      0.0   
180   63    1   0       140   187    0        0      144      1      4.0   
346   50    1   0       150   243    0        0      128      0      2.6   
403   46    0   1       105   204    0        1      172      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
116   63    1   0       130   254    0        0      147      0      1.4   
321   48    0   2       130   275    0        1      139      0      0.2   
920   39    1   0       118   219    0        1      140      0      1.2   
787   51    1   0       140   298    0        1      122      1      4.2   
898   42    0   0       102   265    0        0      122      0      0.6   

     slope  ca  thal  
502      0   0     2  
513      1   1     2  
180      2   2     3  
346      1   0     3  
403      2   0     2  
..     ...  ..   ...  
116      1   1     3  
321      2   0     2  
920      1   0     3  
787      1   3     3  
898      1   0     2  

[257 rows x 13 columns]

In [11]:
y_test

502    1
513    0
180    0
346    0
403    1
      ..
116    0
321    1
920    0
787    0
898    1
Name: target, Length: 257, dtype: int64

In [12]:
x_test = scaler.transform(x_test)
x_test

array([[-0.9153104 , -1.4832397 ,  1.0605507 , ..., -2.23691535,
        -0.72999011, -0.54370213],
       [-0.04571598,  0.67419986, -0.92120827, ..., -0.62834701,
         0.23661749, -0.54370213],
       [ 0.93257773,  0.67419986, -0.92120827, ...,  0.98022133,
         1.20322508,  1.08740427],
       ...,
       [-1.67620551,  0.67419986, -0.92120827, ..., -0.62834701,
        -0.72999011,  1.08740427],
       [-0.37181389,  0.67419986, -0.92120827, ..., -0.62834701,
         2.16983268,  1.08740427],
       [-1.3501076 , -1.4832397 , -0.92120827, ..., -0.62834701,
        -0.72999011, -0.54370213]])

In [13]:
parameters = {'C': [1, 2, 3, 4, 5, 10]}

Logistic_Regression = GridSearchCV(
    LogisticRegression(), param_grid=parameters, cv=5, n_jobs=-1)
Logistic_Regression.fit(x_train, y_train)

print(f'The best parameters are {Logistic_Regression .best_params_}\n')
print(f'The best score is {Logistic_Regression .best_score_}')


lg_clf = Logistic_Regression.best_estimator_

Logistic_Regression_train_accuracy = accuracy_score(
    y_train, lg_clf.predict(x_train))
Logistic_Regression_test_accuracy = accuracy_score(y_test, lg_clf.predict(x_test))


print(
    f'Training Accuracy of Logistic_Regression is {Logistic_Regression_train_accuracy}\n')
print(
    f'Test Accuracy of Logistic_Regression is {Logistic_Regression_test_accuracy } \n')

print(
    f'Confusion Matrix :- \n{confusion_matrix(y_test, lg_clf.predict(x_test))}\n')
print(
    f'Classification Report :- \n {classification_report(y_test, lg_clf.predict(x_test))}')

The best parameters are {'C': 1}

The best score is 0.8491149068322981
Training Accuracy of Logistic_Regression is 0.8603491271820449

Test Accuracy of Logistic_Regression is 0.8171206225680934 

Confusion Matrix :- 
[[101  31]
 [ 16 109]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.86      0.77      0.81       132
           1       0.78      0.87      0.82       125

    accuracy                           0.82       257
   macro avg       0.82      0.82      0.82       257
weighted avg       0.82      0.82      0.82       257



In [14]:
parameters = {'criterion': ['gini', 'entropy'],
              'max_depth': [2, 3, 4, 5, 6],
              'splitter': ['best', 'random'],
              'min_samples_split': [2, 3, 4],
              'min_samples_leaf': [1, 2, 3, 5, 7], }

Decision_tree_clf = GridSearchCV(
    DecisionTreeClassifier(), param_grid=parameters, cv=5, n_jobs=-1)
Decision_tree_clf.fit(x_train, y_train)

print(f'The best parameters are {Decision_tree_clf .best_params_}\n')
print(f'The best score is {Decision_tree_clf .best_score_}')


dt_clf = Decision_tree_clf.best_estimator_

Decision_tree_clf_train_accuracy = accuracy_score(
    y_train, dt_clf.predict(x_train))
Decision_tree_clf_test_accuracy = accuracy_score(y_test, dt_clf.predict(x_test))

print(
    f'Training Accuracy of Decision_tree_clf is {Decision_tree_clf_train_accuracy}\n')
print(
    f'Test Accuracy of Decision_tree_clf is {Decision_tree_clf_test_accuracy} \n')

print(
    f'Confusion Matrix :- \n{confusion_matrix(y_test, dt_clf.predict(x_test))}\n')
print(
    f'Classification Report :- \n {classification_report(y_test, dt_clf.predict(x_test))}')

The best parameters are {'criterion': 'entropy', 'max_depth': 6, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}

The best score is 0.9388742236024845
Training Accuracy of Decision_tree_clf is 0.9812967581047382

Test Accuracy of Decision_tree_clf is 0.9494163424124513 

Confusion Matrix :- 
[[125   7]
 [  6 119]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.95      0.95      0.95       132
           1       0.94      0.95      0.95       125

    accuracy                           0.95       257
   macro avg       0.95      0.95      0.95       257
weighted avg       0.95      0.95      0.95       257



In [15]:
n = list(range(1, 30))

parameters = {'n_neighbors': n}

knn_clf = GridSearchCV(KNeighborsClassifier(),
                       param_grid=parameters, cv=5, n_jobs=-1)
knn_clf.fit(x_train, y_train)

print(f'The best parameters are {knn_clf .best_params_}\n')
print(f'The best score is {knn_clf .best_score_}')


kn_clf = knn_clf.best_estimator_

knn_clf_train_accuracy = accuracy_score(y_train, kn_clf.predict(x_train))
knn_clf_test_accuracy = accuracy_score(y_test, kn_clf.predict(x_test))

print(f'Training Accuracy of knn_clf is {knn_clf_train_accuracy}\n')
print(f'Test Accuracy of knn_clf is {knn_clf_test_accuracy} \n')

print(
    f'Confusion Matrix :- \n{confusion_matrix(y_test, kn_clf.predict(x_test))}\n')
print(
    f'Classification Report :- \n {classification_report(y_test, kn_clf.predict(x_test))}')

The best parameters are {'n_neighbors': 1}

The best score is 0.9700621118012422
Training Accuracy of knn_clf is 1.0

Test Accuracy of knn_clf is 1.0 

Confusion Matrix :- 
[[132   0]
 [  0 125]]

Classification Report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       132
           1       1.00      1.00      1.00       125

    accuracy                           1.00       257
   macro avg       1.00      1.00      1.00       257
weighted avg       1.00      1.00      1.00       257



In [16]:
parameters = {'n_estimators': [10, 17, 25, 33, 41, 48],
              'criterion': ['gini', 'entropy'],
              'max_depth': [2, 3, 4, 5, 6],
              'min_samples_split': [2, 3, 4]}

Random_forest_clf = GridSearchCV(
    RandomForestClassifier(), param_grid=parameters, cv=5, n_jobs=-1)
Random_forest_clf.fit(x_train, y_train)

print(f'The best parameters are {Random_forest_clf .best_params_}\n')
print(f'The best score is {Random_forest_clf .best_score_}')


rf_clf = Random_forest_clf.best_estimator_

Random_forest_clf_train_accuracy = accuracy_score(
    y_train, rf_clf.predict(x_train))
Random_forest_clf_test_accuracy = accuracy_score(y_test, rf_clf.predict(x_test))

print(
    f'Training Accuracy of Random_forest_clf is {Random_forest_clf_train_accuracy}\n')
print(
    f'Test Accuracy of Random_forest_clf is {Random_forest_clf_test_accuracy} \n')

print(
    f'Confusion Matrix :- \n{confusion_matrix(y_test, rf_clf.predict(x_test))}\n')
print(
    f'Classification Report :- \n {classification_report(y_test, rf_clf.predict(x_test))}')

The best parameters are {'criterion': 'entropy', 'max_depth': 6, 'min_samples_split': 2, 'n_estimators': 25}

The best score is 0.9576086956521739
Training Accuracy of Random_forest_clf is 0.9850374064837906

Test Accuracy of Random_forest_clf is 0.9416342412451362 

Confusion Matrix :- 
[[122  10]
 [  5 120]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.96      0.92      0.94       132
           1       0.92      0.96      0.94       125

    accuracy                           0.94       257
   macro avg       0.94      0.94      0.94       257
weighted avg       0.94      0.94      0.94       257



In [17]:
parameters = {'learning_rate': [0.05, 0.10, 0.15, 0.20, 0.25],
              'max_depth': [2, 3, 4, 5, 6, 8, 9],
              'min_child_weight': [1, 3, 4, 5, 7],
              'gamma': [0.3, 0.4, 0.5, 0.7]}

xgboost_clf = GridSearchCV(
    XGBClassifier(), param_grid=parameters, cv=5, n_jobs=-1)
xgboost_clf.fit(x_train, y_train)

print(f'The best parameters are {xgboost_clf .best_params_}\n')
print(f'The best score is {xgboost_clf .best_score_}')


xg_clf = xgboost_clf.best_estimator_

xgboost_clf_train_accuracy = accuracy_score(y_train, xg_clf .predict(x_train))
xgboost_clf_test_accuracy = accuracy_score(y_test, xg_clf .predict(x_test))

print(f'Training Accuracy of xgboost_clf is {xgboost_clf_train_accuracy}\n')
print(f'Test Accuracy of xgboost_clf is {xgboost_clf_test_accuracy} \n')

print(
    f'Confusion Matrix :- \n{confusion_matrix(y_test, xg_clf.predict(x_test))}\n')
print(
    f'Classification Report :- \n {classification_report(y_test, xg_clf.predict(x_test))}')

The best parameters are {'gamma': 0.3, 'learning_rate': 0.15, 'max_depth': 4, 'min_child_weight': 1}

The best score is 0.9762965838509317
Training Accuracy of xgboost_clf is 0.9987531172069826

Test Accuracy of xgboost_clf is 0.9883268482490273 

Confusion Matrix :- 
[[129   3]
 [  0 125]]

Classification Report :- 
               precision    recall  f1-score   support

           0       1.00      0.98      0.99       132
           1       0.98      1.00      0.99       125

    accuracy                           0.99       257
   macro avg       0.99      0.99      0.99       257
weighted avg       0.99      0.99      0.99       257



In [18]:
models = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'Decision Tree Classifier', 'Random Forest Classifier', 'XgBoost'],
    'Train_Score': [Logistic_Regression_train_accuracy, knn_clf_train_accuracy, Decision_tree_clf_train_accuracy, Random_forest_clf_train_accuracy, xgboost_clf_train_accuracy],
    'Test_Score': [Logistic_Regression_test_accuracy, knn_clf_test_accuracy, Decision_tree_clf_test_accuracy, Random_forest_clf_test_accuracy, xgboost_clf_test_accuracy]
})


model_compare = models.sort_values(by='Test_Score', ascending=False)
model_compare

Model  Train_Score  Test_Score
1                       KNN     1.000000    1.000000
4                   XgBoost     0.998753    0.988327
2  Decision Tree Classifier     0.981297    0.949416
3  Random Forest Classifier     0.985037    0.941634
0       Logistic Regression     0.860349    0.817121

In [19]:
pickle_out = open('heart_dis_pred.pkl','wb')
pickle.dump(kn_clf, pickle_out)
pickle_out.close()

In [20]:
x_test[0]

array([-0.9153104 , -1.4832397 ,  1.0605507 ,  0.58896776, -1.32336549,
       -0.41535417, -0.99626012,  0.4489025 ,  1.38971138,  0.29791738,
       -2.23691535, -0.72999011, -0.54370213])

In [22]:
kn_clf.predict([x_test[1]])

array([0], dtype=int64)